bug fixes

diff --git a/mulle-test b/mulle-test
--- a/mulle-test
+++ b/mulle-test
@@ -670,6 +670,12 @@ main()
 #
 #
 #
+_fatal()
+{
+   echo "$0 fatal error: $*" >&2
+   exit 1
+}
+
 _init()
 {
    # mingw stuff
@@ -683,8 +689,7 @@ _init()
    then
       MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
       [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ] && \
-         echo "mulle-bashfunctions-env not installed" >&2 && \
-         exit 1
+         _fatal "mulle-bashfunctions-env not installed"
    fi
 
    . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
