mulle-test is now more or less unaware of mulle-sde and just does its thing

diff --git a/mulle-test b/mulle-test
--- a/mulle-test
+++ b/mulle-test
@@ -115,6 +115,7 @@ Commands:
 Environment:
    MULLE_TEST_DIR          : tests directory (test)
    MULLE_TEST_OBJC_DIALECT : use mulle-objc for mulle-clang
+   MULLE_TEST_CRAFT_BEFORE_RUN : run mulle-test craft before 'run' (like crun)
    PROJECT_DIALECT         : dialect of the tests, can be objc
    PROJECT_EXTENSIONS      : file extensions of the test files
    PROJECT_LANGUAGE        : language of the tests (c)
@@ -289,35 +290,35 @@ test::is_non_environment_commandline()
 }
 
 
-test::exec_in_subshell_if_needed()
-{
-   log_entry "test::exec_in_subshell_if_needed" "$@"
-
-   if test::is_non_environment_commandline "$@"
-   then
-      return
-   fi
-
-   if [ "${MULLE_VIRTUAL_ROOT}" != "${PWD}" ]
-   then
-      if [ ! -z "${MULLE_TEST_DIR}" ]
-      then
-         exekutor cd "${MULLE_TEST_DIR}" || exit 1
-      fi
-      if [ -d "${PWD}/.mulle/share/env" ]
-      then
-         unset MULLE_VIRTUAL_ROOT
-         exekutor exec mulle-sde ${MULLE_TECHNICAL_FLAGS} \
-                           exec mulle-test ${MULLE_TECHNICAL_FLAGS} "$@"
-      else
-         fail "Not a proper initialized test directory (${PWD#"${MULLE_USER_PWD}/"})
-${C_INFO}To initialize for mulle-test:
-${C_RESET_BOLD}   mulle-test init"
-      fi
-   else
-      log_debug "Already in proper subshell ($MULLE_VIRTUAL_ROOT)"
-   fi
-}
+# test::exec_in_subshell_if_needed()
+# {
+#    log_entry "test::exec_in_subshell_if_needed" "$@"
+#
+#    if test::is_non_environment_commandline "$@"
+#    then
+#       return
+#    fi
+#
+#    if [ "${MULLE_VIRTUAL_ROOT}" != "${PWD}" ]
+#    then
+#       if [ ! -z "${MULLE_TEST_DIR}" ]
+#       then
+#          exekutor cd "${MULLE_TEST_DIR}" || exit 1
+#       fi
+#       if [ -d "${PWD}/.mulle/share/env" ]
+#       then
+#          unset MULLE_VIRTUAL_ROOT
+#          exekutor exec mulle-sde ${MULLE_TECHNICAL_FLAGS} \
+#                            exec mulle-test ${MULLE_TECHNICAL_FLAGS} "$@"
+#       else
+#          fail "Not a proper initialized test directory (${PWD#"${MULLE_USER_PWD}/"})
+# ${C_INFO}To initialize for mulle-test:
+# ${C_RESET_BOLD}   mulle-test init"
+#       fi
+#    else
+#       log_debug "Already in proper subshell ($MULLE_VIRTUAL_ROOT)"
+#    fi
+# }
 
 
 test::get_quickstatus()
@@ -597,6 +598,10 @@ test::main()
             break
          ;;
 
+         -*)
+            fail "Unknown option \"$1\""
+         ;;
+
          *)
             break
          ;;
@@ -695,10 +700,18 @@ test::main()
          cmd="run"
       ;;
 
-      'run'|'crun')
+      'crun')
          if [ "${OPTION_CLEAN}" = 'DEFAULT' ]
          then
             OPTION_CLEAN='YES'
+         fi
+         cmd="run"
+      ;;
+
+      'run')
+         if [ "${OPTION_CLEAN}" = 'DEFAULT' ]
+         then
+            OPTION_CLEAN="${MULLE_TEST_CLEAN_BEFORE_RUN:-'YES'}"
          fi
          cmd="run"
       ;;
@@ -729,6 +742,15 @@ test::main()
          cmd="rerun"
       ;;
    esac
+
+#   log_setting "MULLE_VIBECODING='${MULLE_VIBECODING}'"
+#
+#   # escalate to -vv for AI to figure out what stderr and stdout does
+#   if [ "${MULLE_VIBECODING}" = 'YES' ]
+#   then
+#      MULLE_TECHNICAL_FLAGS="-vv ${MULLE_TECHNICAL_FLAGS}"
+#      log_vibe "Set verbosity to at least -vv because MULLE_VIBECODING is YES"
+#   fi
 
    if [ "${OPTION_CLEAN}" = 'DEFAULT' ]
    then
@@ -773,37 +795,37 @@ test::main()
 
    case "${cmd}" in
       craft)
-         # bypass for --help
-         if test::is_non_environment_commandline "$@"
-         then
-            include "test::craft"
-
-            test::craft::main "$@"
-            return
-         fi
-
-         if test::cd_test_dir
-         then
-            test::exec_in_subshell_if_needed "${cmd}" "$@"
-         fi
+         # # bypass for --help
+         # if test::is_non_environment_commandline "$@"
+         # then
+         #    include "test::craft"
+#
+         #    test::craft::main "$@"
+         #    return
+         # fi
+#
+         # if test::cd_test_dir
+         # then
+         #    test::exec_in_subshell_if_needed "${cmd}" "$@"
+         # fi
 
          test::clean "${OPTION_CLEAN}"
          test::do_craft "$@" || return $?
       ;;
 
       run|rerun)
-         # bypass for --help
-         if test::is_non_environment_commandline "$@"
-         then
-            include "test::run"
-            test::run::main "$@"
-            return
-         fi
-
-         if test::cd_test_dir
-         then
-            test::exec_in_subshell_if_needed "${cmd}" "$@"
-         fi
+         # # bypass for --help
+         # if test::is_non_environment_commandline "$@"
+         # then
+         #    include "test::run"
+         #    test::run::main "$@"
+         #    return
+         # fi
+#
+         # if test::cd_test_dir
+         # then
+         #    test::exec_in_subshell_if_needed "${cmd}" "$@"
+         # fi
 
          if [ "${OPTION_CRAFT}" != 'NO' ]
          then
@@ -815,21 +837,21 @@ test::main()
       ;;
 
       clean)
-         if test::cd_test_dir
-         then
-            test::exec_in_subshell_if_needed "${cmd}" "$@"
-         fi
-
+         # if test::cd_test_dir
+         # then
+         #    test::exec_in_subshell_if_needed "${cmd}" "$@"
+         # fi
+#
          include "test::clean"
 
          test::clean::main "$@"
       ;;
 
       coverage)
-         if test::cd_test_dir
-         then
-            test::exec_in_subshell_if_needed "${cmd}" "$@"
-         fi
+        # if test::cd_test_dir
+        # then
+        #    test::exec_in_subshell_if_needed "${cmd}" "$@"
+        # fi
 
          include "test::coverage"
 
@@ -837,10 +859,10 @@ test::main()
       ;;
 
       craftorder)
-         if test::cd_test_dir
-         then
-            test::exec_in_subshell_if_needed "${cmd}" "$@"
-         fi
+         # if test::cd_test_dir
+         # then
+         #    test::exec_in_subshell_if_needed "${cmd}" "$@"
+         # fi
 
          exekutor mulle-sde ${MULLE_TECHNICAL_FLAGS} \
                            craftorder "$@"
@@ -852,10 +874,10 @@ test::main()
 
 
       fetch)
-         if test::cd_test_dir
-         then
-            test::exec_in_subshell_if_needed "${cmd}" "$@"
-         fi
+         # if test::cd_test_dir
+         # then
+         #    test::exec_in_subshell_if_needed "${cmd}" "$@"
+         # fi
 
          exekutor mulle-sde ${MULLE_TECHNICAL_FLAGS} \
                            fetch "$@" 
@@ -874,21 +896,21 @@ test::main()
       ;;
 
       linkorder)
-         if test::cd_test_dir
-         then
-            test::exec_in_subshell_if_needed "${cmd}" "$@"
-         fi
-
+         # if test::cd_test_dir
+         # then
+         #    test::exec_in_subshell_if_needed "${cmd}" "$@"
+         # fi
+#
          include "test::linkorder"
 
          test::linkorder::main "$@"
       ;;
 
       log)
-         if test::cd_test_dir
-         then
-            test::exec_in_subshell_if_needed "${cmd}" "$@"
-         fi
+         # if test::cd_test_dir
+         # then
+         #    test::exec_in_subshell_if_needed "${cmd}" "$@"
+         # fi
 
          exekutor mulle-sde ${MULLE_TECHNICAL_FLAGS} \
                            log "$@"
